-- Convert all timestamp columns to second-level epoch integers
ALTER TABLE "User"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "updatedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "updatedAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "updatedAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "ApiKey"
  ALTER COLUMN "previousKeyExpiresAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "previousKeyExpiresAt")::INTEGER,
  ALTER COLUMN "lastUsedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "lastUsedAt")::INTEGER,
  ALTER COLUMN "expiresAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "expiresAt")::INTEGER,
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "revokedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "revokedAt")::INTEGER;

ALTER TABLE "Project"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "updatedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "updatedAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "updatedAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "Action"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "updatedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "updatedAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "updatedAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "ActionRecord"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "Version"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "Announcement"
  ALTER COLUMN "publishedAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "publishedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "publishedAt")::INTEGER,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "updatedAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "updatedAt")::INTEGER,
  ALTER COLUMN "publishedAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER),
  ALTER COLUMN "updatedAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "Feedback"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);

ALTER TABLE "Log"
  ALTER COLUMN "createdAt" DROP DEFAULT,
  ALTER COLUMN "createdAt" TYPE INTEGER USING EXTRACT(EPOCH FROM "createdAt")::INTEGER,
  ALTER COLUMN "createdAt" SET DEFAULT CAST(EXTRACT(EPOCH FROM now()) AS INTEGER);
